# Generated by Django 3.2.16 on 2022-12-09 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointmentmodel',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookappointmentmodel',
            name='appointment_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
